assign 1: a(variable)에 1(content)을 넣어라  
variable 에는 type 이 존재 (숫자 아니면 문자)
### int= 정수

In [6]:
a = 1; print(type(a))

<class 'int'>


### a를 나타내는 두가지 방법이 존재
→ a 만 써주거나 
→ print (a)

In [7]:
a

1

In [3]:
print(a)

1


;의 역할

In [1]:
a=1;b=2

out 값으로 2만 도출
(cell 의 가장 마지막 값만 도출됨)

In [10]:
a
b

2

따라서 아래 처럼 써주거나 a와 b를 각각 하나의 cell에 입력!

In [11]:
print(a)
print(b)

1
2


### float = 소수점

In [4]:
a = 1; a = float(a); print(type(a))

<class 'float'>


In [5]:
float(a)

1.0

In [12]:
a = 1.2; a = int(a); print(type(a))

<class 'int'>


In [3]:
a=1.1;a=float(a);float(int(a))

1.0

### print(a) vs print (type (a))
a 를 int (정수)라고 설정 - print(a) 라고 하면 1이 도출. 
But, a 를 정수로 보여주는 것 뿐, a 자체가 1이 되는 것은 No.

In [13]:
print(a)

1


### str
content 가 문자 (text) 일때 : ' ' 를 입력  
   
a[1] : 두번째 글자를 지정. 첫번째가 0 부터 시작  
### a[-1] 은 맨 마지막 글자를 지정

In [20]:
a = '123'; print(type(a)); print(a[1])

<class 'str'>
2


### list 를 작성 : [ , ] 를 입력   
list 는 content를 나열하고 싶을 때 사용  
요소의 순서를 관리

In [21]:
a = '123'; a = list(a); print(type(a)); print(a); print(a[2])

<class 'list'>
['1', '2', '3']
3


### List 속에 또다른 list 도 삽입 가능! 즉, 리스트의 element는 variable type 이 달라도 된다
' ' 로 쓰면 숫자가 아니라 문자열을 나타냄  

### List 에서 각 요소에 어떻게 접근할건지! a[0] 은 첫번째 요소 a[-1] 은 맨마지막 요소 : index 를 이용해서 접근

In [22]:
a = [1,'2', [3, '4']]; print(type(a)); print(a[0]); print(a[1]); print(a[2])

<class 'list'>
1
2
[3, '4']


### Tuple (튜플) 은 List 와 거의 흡사  
차이?  1.[ ]이 아닌 ( ) 를 사용 2. 데이터 값의 생성, 삭제, 수정이 불가 

In [14]:
a = (1,'2', [3, '4']); print(type(a)); print(a[0]); print(a[1]); print(a[2])

<class 'tuple'>
1
2
[3, '4']


★ a 의 -1 (맨 마지막) [3,'4']에서 0 (첫 번째)을 나타내줌

In [15]:
a[-1][0]

3

### dict ( dict 은 하나의 pair 설정해준다 )
### index 가 아니라 key 값으로 접근함
print(a["a"]) 
: a 중에서 "a" 의 content를 print 하라 = 표제어로 접근하라

In [24]:
a =	{"a": "apple", "b": "orange", "c": 2014}
print(type(a))
print(a["a"])

<class 'dict'>
apple


아래의 경우는 그냥 index로 접근

In [18]:
a=['apple','banana']

In [19]:
a[0]

'apple'

list []속에 tuple () 이 존재? 행렬 (직사각형의 숫자 배열)과 비슷  
그러나 행렬 그 자체라고 볼 수는 없다.   
, 이하가 (1,2,3) 밑을 이동한다고 생각하면 행렬과 비슷하다  
그러나 파이선에서는 행렬을 자동적으로 실행하는 tool이 없기 때문에 numpy 를 이용해줘야 한다.

In [27]:
a=[(1,2,3), (3,8,0)]
print(type(a))
a

<class 'list'>


[(1, 2, 3), (3, 8, 0)]

import의 기능? 하드디스크에서 필요한 함수를 memory 에 불러와 띄워놓고 사용할 수 있게 해준다  
as 이하는 안써도 무방하지만 간편성을 위해 써주도록 한다

b=np.array(a)  
: . 은 곧 하위폴더를 의미한다. 즉, numpy 폴더 아래에 있는 array 함수를 이용하겠다는 의미이다

In [28]:
import numpy as np
b = np.array(a)
print(b)
print(type(b))

[[1 2 3]
 [3 8 0]]
<class 'numpy.ndarray'>


행렬의 성질상, 2x3과 2x3은 계싼 불가임엗 결과값이 도출되는 것으로 보아 행렬이라고 볼 수 없다.

In [29]:
print(b*b)

[[ 1  4  9]
 [ 9 64  0]]


기존의 값을 행렬로 바꾸기 위해 matrix 함수를 사용해준다.

class 에 대한 이해  
: 함수/variable/syntax 가 파이선의 기본 요소이다  
특정 함수들은 특정 variable과 무리지어 나타나는 경향이 존재한다.  
이를 package처럼 묶어둔 것이 곧 class (객체지향)이다.

In [30]:
c = np.matrix(b)
print(c)
print(type(c))

[[1 2 3]
 [3 8 0]]
<class 'numpy.matrixlib.defmatrix.matrix'>


결과값에 error 가 뜨는 것으로 보아 이는 행렬이라는 것을 알 수 있다. 

In [31]:
c*c

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

.T 는 2x3을 3x2로 변환해줌을 말한다

In [32]:
c*c.T

matrix([[14, 19],
        [19, 73]])